/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const NotesLazyImport = createFileRoute('/notes')()
const NewUserLazyImport = createFileRoute('/new-user')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const NotesLazyRoute = NotesLazyImport.update({
  path: '/notes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/notes.lazy').then((d) => d.Route))

const NewUserLazyRoute = NewUserLazyImport.update({
  path: '/new-user',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/new-user.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/new-user': {
      preLoaderRoute: typeof NewUserLazyImport
      parentRoute: typeof rootRoute
    }
    '/notes': {
      preLoaderRoute: typeof NotesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  NewUserLazyRoute,
  NotesLazyRoute,
])

/* prettier-ignore-end */
