/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NewUserImport } from './routes/new-user'
import { Route as MyGamesImport } from './routes/my-games'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const NewUserRoute = NewUserImport.update({
  path: '/new-user',
  getParentRoute: () => rootRoute,
} as any)

const MyGamesRoute = MyGamesImport.update({
  path: '/my-games',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/my-games': {
      preLoaderRoute: typeof MyGamesImport
      parentRoute: typeof rootRoute
    }
    '/new-user': {
      preLoaderRoute: typeof NewUserImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  MyGamesRoute,
  NewUserRoute,
])

/* prettier-ignore-end */
